#!/usr/bin/env python3
"""
Patches android/app/build.gradle(.kts) (freshly generated by `flutter create`
on every CI run — not committed to git) to add a release signingConfig that
reads from key.properties, so release APKs are signed with a consistent
keystore (constant SHA-1) instead of Flutter's default ephemeral debug key.

Handles both the Groovy DSL (build.gradle) and Kotlin DSL (build.gradle.kts)
templates that different Flutter versions generate.
"""
import os

GRADLE_KTS = "android/app/build.gradle.kts"
GRADLE_GROOVY = "android/app/build.gradle"

path = GRADLE_KTS if os.path.exists(GRADLE_KTS) else GRADLE_GROOVY
is_kts = path == GRADLE_KTS

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

if is_kts:
    header = (
        "import java.util.Properties\n"
        "import java.io.FileInputStream\n\n"
        'val keystoreProperties = Properties()\n'
        'val keystorePropertiesFile = rootProject.file("key.properties")\n'
        "if (keystorePropertiesFile.exists()) {\n"
        "    keystoreProperties.load(FileInputStream(keystorePropertiesFile))\n"
        "}\n\n"
    )
    signing_configs_block = (
        "    signingConfigs {\n"
        '        create("release") {\n'
        '            keyAlias = keystoreProperties["keyAlias"] as String?\n'
        '            keyPassword = keystoreProperties["keyPassword"] as String?\n'
        '            storeFile = keystoreProperties["storeFile"]?.let { file(it as String) }\n'
        '            storePassword = keystoreProperties["storePassword"] as String?\n'
        "        }\n"
        "    }\n\n"
    )
    content = content.replace("android {", header + "android {", 1)
    content = content.replace("    buildTypes {", signing_configs_block + "    buildTypes {", 1)
    if 'signingConfig = signingConfigs.getByName("release")' not in content:
        content = content.replace(
            "getByName(\"release\") {",
            'getByName("release") {\n            signingConfig = signingConfigs.getByName("release")',
            1,
        )
        content = content.replace(
            "\n        release {\n",
            '\n        release {\n            signingConfig = signingConfigs.getByName("release")\n',
            1,
        )
else:
    header = (
        "def keystoreProperties = new Properties()\n"
        "def keystorePropertiesFile = rootProject.file('key.properties')\n"
        "if (keystorePropertiesFile.exists()) {\n"
        "    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))\n"
        "}\n\n"
    )
    signing_configs_block = (
        "    signingConfigs {\n"
        "        release {\n"
        "            keyAlias keystoreProperties['keyAlias']\n"
        "            keyPassword keystoreProperties['keyPassword']\n"
        "            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null\n"
        "            storePassword keystoreProperties['storePassword']\n"
        "        }\n"
        "    }\n\n"
    )
    content = content.replace("android {", header + "android {", 1)
    content = content.replace("    buildTypes {", signing_configs_block + "    buildTypes {", 1)
    if "signingConfig signingConfigs.release" not in content:
        content = content.replace(
            "signingConfig signingConfigs.debug",
            "signingConfig signingConfigs.release",
            1,
        )

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Patched {path}")
print("-" * 40)
print(content)
